main: co.com.cofees.QuickSurvival
version: 0.0.1
name: QuickSurvival
api-version: '1.20'
authors:
  - GerMinatorCofee
  - PyroSoul
  - Strom
commands:
  test:
    description: Pruebas para plugin.
    aliases:
      - prueba
