main: co.com.cofees.QuickSurvival
version: 0.0.1
name: QuickSurvival
api-version: '1.20'
authors:
  - GerMinatorCofee
  - PyroSoul
  - Storm566
commands:
  explosivecows:
    description: "ahora las vacas son explosivas con el click derecho"
    usage: "/explosivecows [true, false]"
    permission: explosivecows.command.cow
    permission-message: "You're not powerful enough to change the cows!!"
  home:
    description: Teleport to your home
    usage: Use /<command> [home]
    aliases:
      - homes
      - h
  Backpack:
    description: abre el backpack manualmente

  inventory:
    description: inventario de prueba

  waystone:
    description: Interactuar Con Waystones
  test:
    description: "Pruebas para plugin."
    aliases:
      - prueba
  eventmenu:
    description: "Abre el menú para configurar el plugin"
    aliases:
      - configmenu
      - em