main: co.com.cofees.QuickSurvival
version: 0.0.1
name: QuickSurvival
api-version: '1.20'
authors:
  - GerMinatorCofee
  - PyroSoul
  - Strom
commands:
  explosivecows:
    description: "ahora las vacas son explosivas con el click derecho"
    usage: "/explosivecows [true, false]"
    permission: explosivecows.command.cow
    permission-message: "You're not powerful enough to change the cows!!"
  test:
    description: "Pruebas para plugin."
    aliases:
      - prueba
