main: co.com.cofees.QuickSurvival
version: 0.0.1
name: QuickSurvival
api-version: '1.20'
authors:
  - GerMinatorCofee
  - PyroSoul
  - Strom
commands:
  home:
    description: Teleport to your home
    usage: /<command> [home]
    aliases:
      - homes
      - h
  qspanel:
    description: abre un panel de control

  Backpack:
    description: abre el backpack manualmente

  inventory:
    description: inventario de prueba

  waystone:
    description: Interactuar Con Waystones
  test:
    description: Pruebas para plugin.
    aliases:
      - prueba

